### ISSUE TITLE
No native module support

### ISSUE THREAD

**Issue by ruipimentel** [Kaffiend/electron-angular-ngrx#7]
Reproduction steps:
1.  Clone and install this seed as described in the [README.md](https://github.com/Kaffiend/electron-angular-ngrx).
1.  On `app.component.ts`, add the following `require()`:
    ```typescript
    const { ipcRenderer } = require('electron');
    ```

With `gulp` command, the following is displayed in red in Electron's console:
`Uncaught TypeError: fs.existsSync is not a function                           vendor.bundle.js:426`

With `ng test` command, the following is displayed in red on the terminal:
`Error: Can't resolve 'fs' in '.../electron-angular-ngrx/node_modules/electron'`

**Comment by Kaffiend** [comment]
Yes, I've solved this challenge, but I had to eject the underlying webpack and build from it to re-integrate HMR and Live reload workflows.

**Comment by ruipimentel** [comment]
Thank you! I'll check this out ASAP :)
